site_name: SCIRecycle Journal
site_description: Turning Today's Garbage into Tomorrow's Citations.
site_author: SCIRecycle Editorial Board

theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide
  font:
    text: Noto Serif SC
    code: Fira Code
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

nav:
  nav:
    - 首页 / HOME: index.md
    - 投稿须知 / SUBMIT: submit.md
    - 第一卷 / VOL 1:
        - 边缘化演变研究: vol1/marginalized-evolution.md